no_resolve: true
domain_set:
- d1q6f0aelx0por.cloudfront.net
- d2wy8f7a9ursnm.cloudfront.net
- d36jcksde1wxzq.cloudfront.net
domain_suffix_set:
- compose-spec.io
- docker.com
- docker.io
- dockerhub.com
domain_keyword_set:
domain_regex_set:
ip_cidr_set:
ip_cidr6_set:
asn_set:
url_regex_set:
