name: Fork Filter lists

on:
  workflow_dispatch:
  schedule:
    - cron: "30 * * * *"
  
jobs:
  Fork-FLITER-list:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
    
    steps: 
    - name: Checkout target repository
      uses: actions/checkout@v4.1.0
    
      # 拉取文件
    - name: 复刻
      run: |
        rm -rf Rules/*
        mkdir -p Rules
        git clone https://github.com/blackmatrix7/ios_rule_script.git BM7_Tmp
        cp -r BM7_Tmp/rule/Surge/* Rules
        rm -rf BM7_Tmp   

      # 改名
    - name: Rename
      run: |
        cd Rules
        find . -type f -name '*.list' -exec sh -c 'mv "$1" "${1%.list}.yaml"' sh {} \;

      # 适配 egern 规则 
    - name: 编辑 
      run: |
        cd Rules
        find . -type f -name '*.yaml' -print0 | while IFS= read -r -d $'\0' file; do
          if [ -f "$file" ]; then
            # 将以"."开头的行的第一个"."替换为 "DOMAIN-SUFFIX"
            sed -i '/^\./s/^\./DOMAIN-SUFFIX,/' "$file"
            # 将除了以 "#" 开头、"空行" 开头之外的行, 在行首添加 "DOMAIN"
            sed -i -E '/^\s*$/b; /^\s*[#;]/b; /^DOMAIN,|^DOMAIN-SUFFIX,|^DOMAIN-KEYWORD,|^DOMAIN-WILDCARD,|^IP-CIDR,|^IP-CIDR6,|^IP-ASN,|^GEOIP,|^AND,|^OR,|^NOT,|^URL-REGEX,|^USER-AGENT,|^PROCESS-NAME,|^DEST-PORT,/b; s/^([^#])/DOMAIN,\1/' "$file"
            # 删除文件中所有 [以 # 或 ; 开头的注释行] + [空行] + [每行中 // 及其后面的内容]
            sed -i -e '/^\s*[#;]/d' -e '/^$/d' -e 's| //.*||'  "$file"
            # 删除指定域名
            sed -i -e '/DOMAIN,this_ruleset_is_made_by_sukkaw.ruleset.skk.moe/d' "$file"
            # 修饰
            sed -i -e '/^USER-AGENT/d' "$file"
            sed -i -e '/^PROCESS-NAME/d' "$file"
            sed -i -e '/^DEST-PORT/d' "$file"
            awk '/^DOMAIN,/ && !added {print "domain_set:"; added=1} {print}' "$file" > tmpfile && mv tmpfile "$file"
            awk '/^DOMAIN-SUFFIX,/ && !added {print "domain_suffix_set:"; added=1} {print}' "$file" > tmpfile && mv tmpfile "$file"
            awk '/^DOMAIN-KEYWORD,/ && !added {print "domain_keyword_set:"; added=1} {print}' "$file" > tmpfile && mv tmpfile "$file"
            awk '/^IP-CIDR,/ && !added {print "ip_cidr_set:"; added=1} {print}' "$file" > tmpfile && mv tmpfile "$file"
            awk '/^IP-CIDR6,/ && !added {print "ip_cidr6_set:"; added=1} {print}' "$file" > tmpfile && mv tmpfile "$file"
            awk '/^IP-ASN,/ && !added {print "asn_set:"; added=1} {print}' "$file" > tmpfile && mv tmpfile "$file"
            awk '/^URL-REGEX,/ && !added {print "url_regex_set:"; added=1} {print}' "$file" > tmpfile && mv tmpfile "$file"
            awk '/^GEOIP,/ && !added {print "geoip_set:"; added=1} {print}' "$file" > tmpfile && mv tmpfile "$file"
          else
            echo "$file not found."
          fi
        done

        for file in Tool-repo/Egern/Rules/*.yaml; do
          if [ -f "$file" ]; then
            if grep -qE '^IP-(ASN|CIDR|CIDR6).*no-resolve$' "$file"; then
            sed -i '1i\no_resolve: true' "$file"
            fi
            sed -i -E 's/^(URL-REGEX,)([^,]+)$/\1"\2"/' "$file"
            sed -i -E 's/^(DOMAIN|DOMAIN-SUFFIX|DOMAIN-KEYWORD|IP-CIDR|IP-CIDR6|IP-ASN|URL-REGEX|GEOIP),/  - /g' "$file"
            sed -i 's/,no-resolve//g' "$file"
            file_names=$(basename "$file" .yaml)
            line_count=$(grep -c '^  - ' "$file")
            awk -v fname="$file_names" 'NR==1 {print "# 规则名称: " fname} {print}' "$file" > tmpfile && mv tmpfile "$file"
            awk -v count="$line_count" 'NR==2 {print "# 规则统计: " count} {print}' "$file" > tmpfile && mv tmpfile "$file"
            sed -i '2a\\' "$file"
          else
            echo "$file not found."
          fi
        done
  
    - name: Edit README
      run: |
        cd Rules
        find . -type f -name 'README.md' -print0 | while IFS= read -r -d $'\0' readme; do
          if [ -f "$readme" ]; then
            # 删除和替换指定的字符串
            sed -i -e '/\*\*MASTER分支 CDN (每日更新)\*\*/d' \
                   -e '/\*\*MASTER分支 GHProxy (每日更新)\*\*/d' \
                   -e '/\(不定时更新\)/d' \
                   -e '/blackmatrix7\/ios_rule_script\/release\/rule\/Surge/d' \
                   -e '/https:\/\/cdn.jsdelivr.net/d' \
                   -e '/https:\/\/ghproxy.com/d' \
                   -e 's|MASTER分支|X分支|g' \
                   -e 's|## Surge## Egern|g' \
                   -e 's|blackmatrix7/ios_rule_script/master/rule/SurgeRepcz/EgernRules/X/Rules|g' \
                   -e '/https:\/\/raw.githubusercontent.com\/blackmatrix7\/ios_rule_script\/release\/rule\/*/d' \
                   -e 's|HOST|DOMAIN|g' \
                   -e 's|IP6-CIDR|IP-CIDR6|g' \
                   -e 's|USER-AGENT|USER-AGENT(Egern不支持)|g' \
                   -e 's|TOTAL|TOTAL(仅供参考)|g' \
                   -e 's|Surge定制化规则|Egern定制化规则|g' \
                   -e 's|Repcz/EgernRules/X/Rules/\(.*\)\.list|Repcz/EgernRules/X/Rules/\1.yaml|g' \
                   -e 's|-\([[:space:]]*\)\([A-Za-z0-9_]*\)\.list|-\1\2.yaml|' \
                   "$readme"
          else
            echo "$readme not found."
          fi
        done

    - name: Push Update
      run: |
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add -A
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git push
        else
          echo "No changes to commit."
        fi

    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
