name: Fork Filter lists

on:
  workflow_dispatch:
  schedule:
    - cron: "30 * * * *"
  
jobs:
  Fork-FLITER-list:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
    
    steps: 
    - name: Checkout target repository
      uses: actions/checkout@v4.1.0
    
      # 拉取文件
    - name: 复刻
      run: |
        rm -rf Rules/*
        mkdir -p Rules
        git clone https://github.com/blackmatrix7/ios_rule_script.git BM7_Tmp
        cp -r BM7_Tmp/rule/Surge/* Rules
        rm -rf BM7_Tmp   

      # 改名
    - name: Rename
      run: |
        cd Rules
        find . -type f -name '*.list' -exec sh -c 'mv "$1" "${1%.list}.yaml"' sh {} \;

      # 适配 egern 规则 
    - name: 编辑 
      run: |
        cd Rules
        find . -type f -name '*.yaml' -print0 | while IFS= read -r -d $'\0' file; do
          if [ -f "$file" ]; then
            # 将以"."开头的行的第一个"."替换为 "DOMAIN-SUFFIX"
            sed -i '/^\./s/^\./DOMAIN-SUFFIX,/' "$file"
            # 将除了以 "#" 开头、"空行" 开头之外的行, 在行首添加 "DOMAIN"
            sed -i -E '/^\s*$/b; /^\s*[#;]/b; /^DOMAIN,|^DOMAIN-SUFFIX,|^DOMAIN-KEYWORD,|^DOMAIN-WILDCARD,|^IP-CIDR,|^IP-CIDR6,|^IP-ASN,|^GEOIP,|^AND,|^OR,|^NOT,|^URL-REGEX,|^USER-AGENT,|^PROCESS-NAME,|^DEST-PORT,/b; s/^([^#])/DOMAIN,\1/' "$file"
            # 删除文件中所有 [以 # 或 ; 开头的注释行] + [空行] + [每行中 // 及其后面的内容]
            sed -i -e '/^\s*[#;]/d' -e '/^$/d' -e 's| //.*||'  "$file"
            # 删除指定域名
            sed -i -e '/DOMAIN,this_ruleset_is_made_by_sukkaw.ruleset.skk.moe/d' "$file"
            # 修饰
            sed -i -e 's/,reject$//' "$file"
            sed -i -E '/^IP-CIDR,/!{/^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+\/[0-9]+/s/^/IP-CIDR,/}' "$file"
            sed -i -E '/^IP-CIDR6,/!{/^[a-fA-F0-9]+:|([a-fA-F0-9]+:+)+[a-fA-F0-9]+\/[0-9]+/s/^/IP-CIDR6,/}' "$file"
            awk '
            /^DOMAIN,/         { print "0 " $0; next }
            /^DOMAIN-SUFFIX,/  { print "1 " $0; next }
            /^DOMAIN-KEYWORD,/ { print "2 " $0; next }
            /^DOMAIN-WILDCARD,/{ print "3 " $0; next }
            /^IP-CIDR,/        { print "4 " $0; next }
            /^IP-CIDR6,/       { print "5 " $0; next }
            /^IP-ASN,/         { print "6 " $0; next }
            /^PROCESS-NAME,/   { print "7 " $0; next }
            /^URL-REGEX,/      { print "8 " $0; next }
            /^USER-AGENT,/     { print "9 " $0; next }
            /^GEOIP,/          { print "10 " $0; next }
            /^AND,/            { print "11 " $0; next }
            /^OR,/             { print "12 " $0; next }
            /^NOT,/            { print "13 " $0; next }
            /^DEST-PORT,/      { print "14 " $0; next }
                               { print "15 " $0; next }
            ' "$file" | sort -k1,1n -k2,2 | cut -d' ' -f2- > "$file.sorted" && mv "$file.sorted" "$file"
            awk '!seen[tolower($0)]++' "$file" > temp && mv temp "$file"
          else
            echo "$file not found."
          fi
        done
  
    - name: Edit README
      run: |
        cd Rules
        find . -type f -name 'README.md' -print0 | while IFS= read -r -d $'\0' readme; do
          if [ -f "$readme" ]; then
            # 删除和替换指定的字符串
            sed -i -e '/\*\*MASTER分支 CDN (每日更新)\*\*/d' \
                   -e '/\*\*MASTER分支 GHProxy (每日更新)\*\*/d' \
                   -e '/\(不定时更新\)/d' \
                   -e '/blackmatrix7\/ios_rule_script\/release\/rule\/QuantumultX/d' \
                   -e '/https:\/\/cdn.jsdelivr.net/d' \
                   -e '/https:\/\/ghproxy.com/d' \
                   -e 's|MASTER分支|X分支|g' \
                   -e 's|## QuantumultX|## Egern|g' \
                   -e 's|blackmatrix7/ios_rule_script/master/rule/QuantumultX|Repcz/EgernRules/X/Rules|g' \
                   -e 's|github.com/blackmatrix7/ios_rule_script/tree/master/rule/QuantumultX|github.com/Repcz/EgernRules/tree/X/Rules|g' \
                   -e 's|HOST|DOMAIN|g' \
                   -e 's|IP6-CIDR|IP-CIDR6|g' \
                   -e 's|USER-AGENT|USER-AGENT(Egern不支持)|g' \
                   -e 's|TOTAL|TOTAL(仅供参考)|g' \
                   -e 's|QuantumultX定制化规则|Egern定制化规则|g' \
                   -e 's|Repcz/EgernRules/X/Rules/\(.*\)\.list|Repcz/EgernRules/X/Rules/\1.yaml|g' \
                   -e 's|-\([[:space:]]*\)\([A-Za-z0-9_]*\)\.list|-\1\2.yaml|' \
                   "$readme"
          else
            echo "$readme not found."
          fi
        done

    - name: Push Update
      run: |
        cd EgernRules-repo
          if [[ -n $(git status -s) ]]; then
            git config --local user.email "${{ github.actor }}@users.noreply.github.com"
            git config --local user.name "${{ github.actor }}"
            git add -A
            git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')"
            git push origin X
          else
            echo "No changes to commit."
          fi

    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
