name: Fork Filter lists

on:
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * *"
  
jobs:
  Fork-FLITER-list:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.2.2
      with:
        repository: Repcz/EgernRules
        path: EgernRules-repo
  
    # 拉取文件
    - name: Clone
      run: |
        rm -rf Rules/*
        mkdir -p Rules
        git clone https://github.com/blackmatrix7/ios_rule_script.git BM7_Tmp
        cp -r BM7_Tmp/rule/Surge/* Rules
        rm -rf BM7_Tmp   

    # 适配 egern 规则 
    - name: Edit
      run: |
        find EgernRules-repo/Rules -type f -name "*.list" | while read -r file; do
          if [ -f "$file" ]; then
            # 删除不需要的行
            sed -i -e '/^USER-AGENT/d' "$file"
            sed -i -e '/^PROCESS-NAME/d' "$file"
            sed -i -e '/^DEST-PORT/d' "$file"
            sed -i -e '/^\s*[#;]/d' -e '/^$/d' -e 's| //.*||'  "$file"

            # 将 .list 文件转换为 .yaml 文件
            yaml_file="${file%.list}.yaml"
            echo "# 规则名称: $(basename "$yaml_file" .yaml)" > "$yaml_file"
            echo "# 规则统计: $(grep -c '^DOMAIN\|^DOMAIN-SUFFIX\|^DOMAIN-KEYWORD\|^IP-CIDR\|^IP-CIDR6\|^IP-ASN\|^URL-REGEX\|^GEOIP' "$file")" >> "$yaml_file"
            echo "" >> "$yaml_file"

            # 提取并格式化规则
            awk '/^DOMAIN,/ && !added {print "domain_set:"; added=1} {print}' "$file" | grep '^DOMAIN,' | sed 's/^DOMAIN,/  - /' >> "$yaml_file"
            awk '/^DOMAIN-SUFFIX,/ && !added {print "domain_suffix_set:"; added=1} {print}' "$file" | grep '^DOMAIN-SUFFIX,' | sed 's/^DOMAIN-SUFFIX,/  - /' >> "$yaml_file"
            awk '/^DOMAIN-KEYWORD,/ && !added {print "domain_keyword_set:"; added=1} {print}' "$file" | grep '^DOMAIN-KEYWORD,' | sed 's/^DOMAIN-KEYWORD,/  - /' >> "$yaml_file"
            awk '/^IP-CIDR,/ && !added {print "ip_cidr_set:"; added=1} {print}' "$file" | grep '^IP-CIDR,' | sed 's/^IP-CIDR,/  - /' >> "$yaml_file"
            awk '/^IP-CIDR6,/ && !added {print "ip_cidr6_set:"; added=1} {print}' "$file" | grep '^IP-CIDR6,' | sed 's/^IP-CIDR6,/  - /' >> "$yaml_file"
            awk '/^IP-ASN,/ && !added {print "asn_set:"; added=1} {print}' "$file" | grep '^IP-ASN,' | sed 's/^IP-ASN,/  - /' >> "$yaml_file"
            awk '/^URL-REGEX,/ && !added {print "url_regex_set:"; added=1} {print}' "$file" | grep '^URL-REGEX,' | sed 's/^URL-REGEX,/  - /' >> "$yaml_file"
            awk '/^GEOIP,/ && !added {print "geoip_set:"; added=1} {print}' "$file" | grep '^GEOIP,' | sed 's/^GEOIP,/  - /' >> "$yaml_file"
            
            # 删除原始的 .list 文件
            rm "$file"
            
            # 处理生成的 .yaml 文件
            if grep -qE '^IP-(ASN|CIDR|CIDR6).*no-resolve$' "$yaml_file"; then
              sed -i '1i\no_resolve: true' "$yaml_file"
            fi
            sed -i -E 's/^(URL-REGEX,)([^,]+)$/\1"\2"/' "$yaml_file"
            sed -i -E 's/^(DOMAIN|DOMAIN-SUFFIX|DOMAIN-KEYWORD|IP-CIDR|IP-CIDR6|IP-ASN|URL-REGEX|GEOIP),/  - /g' "$yaml_file"
            sed -i 's/,no-resolve//g' "$yaml_file"
            file_names=$(basename "$yaml_file" .yaml)
            line_count=$(grep -c '^  - ' "$yaml_file")
            awk -v fname="$file_names" 'NR==1 {print "# 规则名称: " fname} {print}' "$yaml_file" > tmpfile && mv tmpfile "$yaml_file"
            awk -v count="$line_count" 'NR==2 {print "# 规则统计: " count} {print}' "$yaml_file" > tmpfile && mv tmpfile "$yaml_file"
            sed -i '2a\\' "$yaml_file"
          else
            echo "$file not found."
          fi
        done
  
    - name: Edit README
      run: |
        find EgernRules-repo/Rules -type f -name "README.md" | while read -r file; do
          if [ -f "$file" ]; then
            # 删除和替换指定的字符串
            sed -i -e '/\*\*MASTER分支 CDN (每日更新)\*\*/d' \
                   -e '/\*\*MASTER分支 GHProxy (每日更新)\*\*/d' \
                   -e '/\(不定时更新\)/d' \
                   -e '/blackmatrix7\/ios_rule_script\/release\/rule\/Surge/d' \
                   -e '/https:\/\/cdn.jsdelivr.net/d' \
                   -e '/https:\/\/ghproxy.com/d' \
                   -e 's|MASTER分支|X分支|g' \
                   -e 's|## Surge## Egern|g' \
                   -e 's|blackmatrix7/ios_rule_script/master/rule/SurgeRepcz/EgernRules/X/Rules|g' \
                   -e '/https:\/\/raw.githubusercontent.com\/blackmatrix7\/ios_rule_script\/release\/rule\/*/d' \
                   -e 's|HOST|DOMAIN|g' \
                   -e 's|IP6-CIDR|IP-CIDR6|g' \
                   -e 's|USER-AGENT|USER-AGENT(Egern不支持)|g' \
                   -e 's|TOTAL|TOTAL(仅供参考)|g' \
                   -e 's|Surge定制化规则|Egern定制化规则|g' \
                   -e 's|Repcz/EgernRules/X/Rules/\(.*\)\.list|Repcz/EgernRules/X/Rules/\1.yaml|g' \
                   -e 's|-\([[:space:]]*\)\([A-Za-z0-9_]*\)\.list|-\1\2.yaml|' \
                   "$file"
          else
            echo "$file not found."
          fi
        done

    - name: Push Update
      run: |
        cd EgernRules-repo
          if [[ -n $(git status -s) ]]; then
            git config --local user.email "${{ github.actor }}@users.noreply.github.com"
            git config --local user.name "${{ github.actor }}"
            git add -A
            git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')"
            git push origin X
          else
            echo "No changes to commit."
          fi

    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
